# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: slick_map_css-rails 0.1.2 ruby lib

Gem::Specification.new do |s|
  s.name = "slick_map_css-rails"
  s.version = "0.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib"]
  s.authors = ["David DIDIER"]
  s.date = "2016-01-08"
  s.description = "A stylesheet for displaying site maps directly from HTML unordered list (adapted from http://astuteo.com/slickmap/)"
  s.email = "c_inconnu2@yahoo.fr"
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.md"
  ]
  s.files = [
    ".document",
    ".ruby-gemset",
    ".ruby-version",
    "Gemfile",
    "Gemfile.lock",
    "Guardfile",
    "LICENSE.txt",
    "README.md",
    "Rakefile",
    "VERSION",
    "doc/index.html",
    "lib/slick_map_css-rails.rb",
    "lib/slick_map_css-rails/engine.rb",
    "slick_map_css-rails.gemspec",
    "spec/spec_helper.rb",
    "vendor/assets/images/L1-center.png",
    "vendor/assets/images/L1-left.png",
    "vendor/assets/images/L1-right.png",
    "vendor/assets/images/L3-bottom.png",
    "vendor/assets/images/L3-center.png",
    "vendor/assets/images/L3-li-top.png",
    "vendor/assets/images/L3-ul-top.png",
    "vendor/assets/images/vertical-line.png",
    "vendor/assets/images/white-highlight.png",
    "vendor/assets/stylesheets/slick_map_css-rails.css.scss"
  ]
  s.homepage = "http://github.com/ddidier/slick_map_css-rails"
  s.licenses = ["MIT"]
  s.rubygems_version = "2.5.0"
  s.summary = "A stylesheet for displaying site maps directly from HTML unordered list"

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, [">= 3.2.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.10"])
      s.add_development_dependency(%q<capybara>, ["~> 2.5"])
      s.add_development_dependency(%q<guard>, ["~> 2.13"])
      s.add_development_dependency(%q<guard-bundler>, ["~> 2.0"])
      s.add_development_dependency(%q<guard-rspec>, ["~> 4.6"])
      s.add_development_dependency(%q<guard-spork>, ["~> 2.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_development_dependency(%q<rdoc>, ["~> 4.1"])
      s.add_development_dependency(%q<rspec-rails>, ["~> 3.3"])
      s.add_development_dependency(%q<sqlite3>, ["~> 1.3"])
      s.add_development_dependency(%q<spork>, ["~> 0.9"])
      s.add_development_dependency(%q<yard>, ["~> 0.8"])
    else
      s.add_dependency(%q<rails>, [">= 3.2.0"])
      s.add_dependency(%q<bundler>, ["~> 1.10"])
      s.add_dependency(%q<capybara>, ["~> 2.5"])
      s.add_dependency(%q<guard>, ["~> 2.13"])
      s.add_dependency(%q<guard-bundler>, ["~> 2.0"])
      s.add_dependency(%q<guard-rspec>, ["~> 4.6"])
      s.add_dependency(%q<guard-spork>, ["~> 2.0"])
      s.add_dependency(%q<jeweler>, ["~> 2.0"])
      s.add_dependency(%q<rdoc>, ["~> 4.1"])
      s.add_dependency(%q<rspec-rails>, ["~> 3.3"])
      s.add_dependency(%q<sqlite3>, ["~> 1.3"])
      s.add_dependency(%q<spork>, ["~> 0.9"])
      s.add_dependency(%q<yard>, ["~> 0.8"])
    end
  else
    s.add_dependency(%q<rails>, [">= 3.2.0"])
    s.add_dependency(%q<bundler>, ["~> 1.10"])
    s.add_dependency(%q<capybara>, ["~> 2.5"])
    s.add_dependency(%q<guard>, ["~> 2.13"])
    s.add_dependency(%q<guard-bundler>, ["~> 2.0"])
    s.add_dependency(%q<guard-rspec>, ["~> 4.6"])
    s.add_dependency(%q<guard-spork>, ["~> 2.0"])
    s.add_dependency(%q<jeweler>, ["~> 2.0"])
    s.add_dependency(%q<rdoc>, ["~> 4.1"])
    s.add_dependency(%q<rspec-rails>, ["~> 3.3"])
    s.add_dependency(%q<sqlite3>, ["~> 1.3"])
    s.add_dependency(%q<spork>, ["~> 0.9"])
    s.add_dependency(%q<yard>, ["~> 0.8"])
  end
end

